/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonTest: typeof import('./src/components/ButtonTest.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    FabButton: typeof import('./src/components/FabButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
  }
}
